---

- name: update packages
  become: yes
  apt:
    update_cache: yes

- name: install apache2
  become: yes
  apt:
    name: ["apache2"]
    state: latest

- name: copying files to apache
  become: yes
  copy:
    src: index.html
    dest: /var/www/html/index.html