version: 2.1

jobs:
  run-aws:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          command: aws help > ~/file.txt
      - save_cache:
          key: mysavedoutput1
          paths:
            - ~/file.txt

  test-caching:
    docker:
      - image: cimg/go:1.16
    steps:
      - restore_cache:
          keys:
            - mysavedoutput1
      - run:
          command: cat ~/file.txt

workflows:
  workflow-X:
    jobs:
      - run-aws
      - test-caching:
          requires:
            - run-aws