version: 2.1

jobs:
  instance_creation:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: |
            aws cloudformation deploy \
            --stack-name my-stack \
            --template-file instance.yaml \

  configure_instance:
    docker: 
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - add_ssh_keys:
          ec2: ["1a:2e:1f:f6:4d:41:a3:97:df:dd:4c:6f:cd:f5:2b:40"]
      - run:
          command: sudo apt-get update
      - run: 
          command: |
            sudo apt-get install ansible
      - run:
          command: |
            ansible-playbook web playbook.yaml

  instance_delete:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: aws cloudformation delete-stack --stack-name my-stack


workflows:
  starting-up-instance:
    jobs:
      - instance_creation
      - configure_instance:
          requires:
            - instance_creation