version: 2.1

jobs:
  test:
    docker:
      - image: circleci:node:13.8.0
    branches:
      only:
        - master
    steps:
      - run: echo "Hello world"

workflows:
  welcome:
    jobs:
      - test