version: 2.1

jobs:
  run-aws:
    docker:
      - image: amazon/aws-cli
      - image: cimg/go:1.16
    steps:
      - run:
          command: aws help > ~/file.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - file.txt

  test-caching:
    docker:
      - image: cimg/go:1.16
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: cat ~/file.txt

workflows:
  workflow-X:
    jobs:
      - run-aws
      - test-caching:
          requires:
            - run-aws