version: 2.1

jobs:
  instance_creation:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: |
            aws cloudformation deploy \
            --stack-name my-stack \
            --template-body instance.yaml \


workflows:
  workflow-X:
    jobs:
      - instance_creation